apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
  namespace: flask-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
        - name: flask-app
          image: docker.io/samgabrail/flask-todo:v0.0.9
          env:
            - name: DB_HOST
              value: mysql-flask-todo
            - name: DB_NAME
              value: todos
            - name: DYNAMIC_SECRET_TTL
              value: "3600"
            - name: FLASK_APP
              value: run.py
            - name: ENVIRONMENT
              value: remote
            - name: AKEYLESS_K8S_AUTH_ID
              value: p-83ve3ht3d7zukm
            - name: AKEYLESS_GATEWAY_URL
              value: https://animated-space-potato-4grg9r75r6w35qq6-8000.app.github.dev
            - name: AKEYLESS_GATEWAY_API_URL
              value: https://animated-space-potato-4grg9r75r6w35qq6-8081.app.github.dev
            - name: AKEYLESS_K8S_AUTH_CONFIG_NAME
              value: /Workshops/Workshop2/tekanaid/k8s-auth-method
            - name: DATABASE_DYNAMIC_SECRET_NAME
              value: /Workshops/Workshop2/tekanaid/mysql_password_dynamic
          ports:
            - containerPort: 8080
