apiVersion: v1
kind: Service
metadata:
  name: mysql-flask-todo
  namespace: flask-todo
spec:
  selector:
    app: mysql-flask-todo
  ports:
  - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo
  namespace: flask-todo
spec:
  selector:
    app: flask-todo
  ports:
  - port: 80
    targetPort: 8080
